### ISSUE TITLE
panic: reading varint: buffer too small

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-threads#234]
Unfortunately, I don't have much to provide for this one. It happened while running android test suites against the daemon, but I didn't notice immediately when it happened so don't know the source of the call or payload sent. 

```
go-threads(master)$ go run threadsd/main.go 
Welcome to Threads!
Your peer ID is 12D3KooWQHdn7kuFXLeQJoemcWLZye2a4isdfYk5JTH2wjUz6XfW
panic: reading varint: buffer too small

goroutine 4382004 [running]:
github.com/multiformats/go-multiaddr.(*Component).Value(0xc00c29f7e8, 0x1d41b8d, 0x6)
	/Users/andrewhill/go/pkg/mod/github.com/multiformats/go-multiaddr@v0.2.0/component.go:114 +0xcd
github.com/multiformats/go-multiaddr.(*Component).writeTo(0xc00c29f7e8, 0xc00c29f7c8)
	/Users/andrewhill/go/pkg/mod/github.com/multiformats/go-multiaddr@v0.2.0/component.go:130 +0x121
github.com/multiformats/go-multiaddr.bytesToString(0xc006cc6b71, 0x3, 0x3, 0x3, 0x31, 0x34, 0xc006380df8)
	/Users/andrewhill/go/pkg/mod/github.com/multiformats/go-multiaddr@v0.2.0/codec.go:159 +0x8e
github.com/multiformats/go-multiaddr.(*multiaddr).String(0xc00ea76f80, 0x2017da0, 0xc0082eecb0)
	/Users/andrewhill/go/pkg/mod/github.com/multiformats/go-multiaddr@v0.2.0/multiaddr.go:62 +0x44
github.com/textileio/go-threads/api.(*service).GetStoreLink(0xc0065400d0, 0x2006ce0, 0xc00de4d680, 0xc00de4d6e0, 0xc0065400d0, 0xc00de4d680, 0xc006388a80)
	/Users/andrewhill/Textile/go-threads/api/service.go:91 +0x347
github.com/textileio/go-threads/api/pb._API_GetStoreLink_Handler(0x1d05580, 0xc0065400d0, 0x2006ce0, 0xc00de4d680, 0xc0065d12c0, 0x0, 0x2006ce0, 0xc00de4d680, 0xc00b7dd230, 0x26)
	/Users/andrewhill/Textile/go-threads/api/pb/api.pb.go:2313 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc006273c80, 0x2013f40, 0xc00c1aa180, 0xc0090bfc00, 0xc0064e15f0, 0x28b3460, 0x0, 0x0, 0x0)
	/Users/andrewhill/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1007 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc006273c80, 0x2013f40, 0xc00c1aa180, 0xc0090bfc00, 0x0)
	/Users/andrewhill/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:1287 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00f0068d0, 0xc006273c80, 0x2013f40, 0xc00c1aa180, 0xc0090bfc00)
	/Users/andrewhill/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/andrewhill/go/pkg/mod/google.golang.org/grpc@v1.25.1/server.go:720 +0xa1
exit status 2
```

**Comment by shc261392** [comment]
I just found that this issue can always be reproduced by calling the `GetStoreLink` gRPC API.

**Comment by andrewxhill** [comment]
which client are you running?

**Comment by shc261392** [comment]
I'm running with both the Android client and JS client.

To reproduce this in the JS client, add

```
invites = await client.getStoreLink(storeID)
```

in the https://github.com/textileio/js-threads-client/blob/master/examples/browser/index.html after the client is created.

For Android client

```
GetStoreLinkReply invites = client.GetStoreLinkSync(storeId);
```

**Comment by shc261392** [comment]
Found that missing a `Start()` API call before getting the store link causes this issue.

```
await client.start(storeID)
invites = await client.getStoreLink(storeID)
```

and it works 🎉

**Comment by andrewxhill** [comment]
Ah yes! Glad you got that. 

We'll need to figure out a better error message for non-started stores.
