### ISSUE TITLE
cant't create already existent instance

### ISSUE THREAD

**Issue by ystyle** [textileio/go-threads#325]
i has two node of my app

node A is on a ECS
node B run in local 

When I add a record on node B, nodeA occasionally gets an error, and app exited
```
2020-04-29T14:18:50.490+0800	FATAL	store	store/storethread.go:130	cant't create already existent instance
github.com/textileio/go-threads/store.(*singleThreadAdapter).threadToStore
	/home/ystyle/go/pkg/mod/github.com/textileio/go-threads@v0.1.4/store/storethread.go:130
```

init store
![2020-04-29_14-22](https://user-images.githubusercontent.com/4478635/80566320-49838300-8a25-11ea-8d5d-79c3349b23e1.png)

add a file and a record
![2020-04-29_14-22_1](https://user-images.githubusercontent.com/4478635/80566307-44becf00-8a25-11ea-8ebb-a7364128ac51.png)

**Comment by asutula** [comment]
Hi @ystyle. It looks like you're using an old version of go-threads. Can you update to the latest version and let's go from there?

**Comment by ystyle** [comment]
thanks.

PS: 
the latest version， I need a fixed thread-id, I need to save it myself？

**Comment by ystyle** [comment]
go-threads version:  v0.1.16 , has the same issue

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xe0f165]

goroutine 3090 [running]:
github.com/textileio/go-threads/db.(*Collection).Indexes(0x0, 0x67e8eb570c71078c)
        /home/lxy/go/pkg/mod/github.com/textileio/go-threads@v0.1.16/db/collection.go:88 +0x5
github.com/textileio/go-threads/db.indexDelete(0x139cce0, 0x0, 0x13b7720, 0xc004aef280, 0xc004ae96b0, 0x2e, 0x0, 0x0, 0x0, 0xc001c7ad80, ...)
        /home/lxy/go/pkg/mod/github.com/textileio/go-threads@v0.1.16/db/index.go:67 +0x4c
github.com/textileio/go-threads/db.defaultIndexFunc.func1(0xc004ee9aac, 0x4, 0xc004ae96b0, 0x2e, 0x0, 0x0, 0x0, 0xc001c7ad80, 0xba, 0xba, ...)
        /home/lxy/go/pkg/mod/github.com/textileio/go-threads@v0.1.16/db/db.go:431 +0xd0
github.com/textileio/go-threads/jsonpatcher.(*jsonPatcher).Reduce(0x1c95350, 0xc0054c07a0, 0x1, 0x1, 0x13b8500, 0xc0018e1c20, 0xc0002bacc0, 0xe, 0xc0054c08d0, 0x0, ...)
        /home/lxy/go/pkg/mod/github.com/textileio/go-threads@v0.1.16/jsonpatcher/jsonpatcher.go:126 +0x1001
github.com/textileio/go-threads/db.(*DB).Reduce(0xc00199c180, 0xc0054c07a0, 0x1, 0x1, 0xc001e10fb8, 0xa11d1a)
        /home/lxy/go/pkg/mod/github.com/textileio/go-threads@v0.1.16/db/db.go:262 +0xb8
github.com/textileio/go-threads/db.(*dispatcher).Dispatch.func1(0x1, 0xa)
        /home/lxy/go/pkg/mod/github.com/textileio/go-threads@v0.1.16/db/dispatcher.go:95 +0x4a
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0054c2ea0, 0xc0054c2ed0)
        /home/lxy/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/lxy/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

**Comment by sanderpick** [comment]
@ystyle would you mind sharing some copyable code (rather than an image)?

**Comment by ystyle** [comment]
The code is almost the same: 
https://gitee.com/ystyle/textile-demo

**Comment by sanderpick** [comment]
Cool! Thanks for sharing. I have one of your file sharing nodes on GCC, and one locally. I'm seeing the uploaded files replicate, but haven't seen the fatal error yet. How often are you seeing the crash?

**Comment by ystyle** [comment]
Yes, now the files uploaded by both nodes can be synchronized with each other

**Comment by sanderpick** [comment]
Great! Let me know if you see this fatal error again. Still unable to reproduce here.
